CREATE TABLE IF NOT EXISTS language_settings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    mode VARCHAR(10) NOT NULL DEFAULT 'multi',
    enabled_locales JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
